---
title: "p8105_hw3_hy2912"
author: "Helen Yousaf"
date: "2024-10-04"
output: html_document
---
```{r}
library(readr)
library(tidyverse)
library(ggridges)
```

# Problem 1 
#### NY NOAA Data 
```{r}
library(p8105.datasets)
  data("ny_noaa")
```

# Problem 2 
#### MIMS Data

Importing MIMS Demographic data
```{r}
MIMS_dg_df = 
  read_csv(file = "/Users/helenyousaf/Desktop/p8105_hw3_hy2912/MIMS.dg.csv", 
           skip = 4, na = c(".", "NA", ""), 
    col_types = cols(
      'SEQN' = col_character(),
      `sex` = col_character(),
      `age` = col_integer(),
      `BMI` = col_double(),
      `education` = col_character(),
    )
  )
```

```{r}
names(MIMS_dg_df)
MIMS_df_df = janitor::clean_names(MIMS_dg_df)
```

Importing MIMS Accelerometer data 
```{r}
MIMS_ac_df = 
  read_csv(file = "/Users/helenyousaf/Desktop/p8105_hw3_hy2912/MIMS.ac.csv", 
           na = c(".", "NA", ""), 
     col_types = cols(
      'SEQN' = col_character(),
    )
  )       
```

```{r}
names(MIMS_ac_df)
MIMS_ac_df = janitor::clean_names(MIMS_ac_df)
```

Joining data sets
```{r}
nhanes_data <- MIMS_dg_df |>
  filter(age >= 21) |>
  drop_na() |>
  left_join(MIMS_ac_df, by = "seqn") |>
  mutate(
    gender = factor(sex, levels = c("1", "2")),
    education = factor(education, levels = c("1", "2", "3"))
  )
```


# Problem 3
#### Citi Bike Data 

Loading data sets 
```{r}
Jan2020_df = read_csv(file = "/Users/helenyousaf/Desktop/p8105_hw3_hy2912/Jan2020.CITI.csv", na = c(".", "NA", ""))
Jul2020_df = read_csv(file = "/Users/helenyousaf/Desktop/p8105_hw3_hy2912/July2020.CITI.csv", na = c(".", "NA", ""))
Jan2024_df = read_csv(file = "/Users/helenyousaf/Desktop/p8105_hw3_hy2912/Jan2024.CITI.csv", na = c(".", "NA", ""))
Jul2024_df = read_csv(file = "/Users/helenyousaf/Desktop/p8105_hw3_hy2912/July2024.CITI.csv", na = c(".", "NA", ""))
```
Basic cleaning of data sets
```{r}
Jan2020_df = janitor::clean_names (Jan2020_df)
names(Jan2020_df)
```
```{r}
Jul2020_df = janitor::clean_names (Jul2020_df)
names(Jul2020_df)
```
```{r}
Jan2024_df = janitor::clean_names (Jan2024_df)
names(Jan2024_df)
```
```{r}
Jul2024_df = janitor::clean_names (Jul2024_df)
names(Jul2024_df)
```

```{r}
Jan2020_df = drop_na(Jan2020_df)
```

```{r}
Jan2020_df = 
  col_types = cols(
      member_casual = col_character() 
  )
```

```{r}
Jan2020_df = 
  mutate(
    member_casual = 
      case_match(
        member_casual, 
        1 ~ "casual", 
        2 ~ "member")
  
```
  

